DOCUMENT_TITLE_MAX_LENGTH = 255
DOCUMENT_FILENAME_MAX_LENGTH = 255
DOCUMENT_MIME_TYPE_MAX_LENGTH = 128
DOCUMENT_SEARCH_KEYWORD_MAX_LENGTH = 255
NOTE_CONTENT_MAX_LENGTH = 200_000
DOCUMENT_LIST_SUMMARY_PREVIEW_MAX_LENGTH = 500
DOCUMENT_LIST_ERROR_PREVIEW_MAX_LENGTH = 500
DOCUMENT_SUMMARY_MAX_LENGTH = 20_000
RELATED_DOCUMENT_BODY_QUERY_MAX_LENGTH = 2_000
DOCUMENT_DETAIL_CONTENT_PAGE_MAX_LENGTH = 50_000
DOCUMENT_DETAIL_CONTENT_OFFSET_MAX = 100_000_000
USER_AVATAR_URL_MAX_LENGTH = 2_048

DOCUMENT_TAG_LIMIT = 20
TAG_NAME_MAX_LENGTH = 64
UPLOAD_TAGS_FORM_MAX_LENGTH = 2048

CHAT_SCOPE_DOCUMENT_LIMIT = 100
CHAT_SCOPE_TAG_LIMIT = 20
CHAT_SCOPE_SOURCE_TYPE_LIMIT = 11
CHAT_CITATION_LIMIT = 8
CHAT_CITATION_TEXT_MAX_LENGTH = 223
CHAT_ANSWER_MAX_LENGTH = 32_000
CHAT_HISTORY_CONTEXT_MESSAGE_MAX_LENGTH = 2_000
MESSAGE_LIST_CONTENT_PREVIEW_MAX_LENGTH = CHAT_ANSWER_MAX_LENGTH
RAG_CONTEXT_MAX_LENGTH = 6_000
RETRIEVAL_CHUNK_CONTENT_MAX_LENGTH = RAG_CONTEXT_MAX_LENGTH
JOB_MESSAGE_MAX_LENGTH = 255
JOB_ERROR_MESSAGE_MAX_LENGTH = 4_000

ORGANIZE_RESULT_MAX_LENGTH = NOTE_CONTENT_MAX_LENGTH
ENRICHMENT_TAG_OUTPUT_MAX_LENGTH = 4_000
